FROM python:3.10.12

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        sqitch \
        postgresql-client && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
